WIP: Continue setting up Test Compatibility Kit
Requires JAVA_HOME (e. g. /usr/lib/jvm/java-11-graalvm) and GRAAL_HOME
(e. g. ~/git/graal) to be set. The two GraalVM jars are built by running
`mx build` in $GRAAL_HOME/truffle. truffle-tck-tests.jar contains the
actual JUnit tests (without it, there is not much to do); graal-sdk.jar
should contain org.graalvm.polyglot.Value and other relevant classes,
but I still get this error:

    There were 2 failures:
    1) testForValue(com.oracle.truffle.tck.tests.TypeDescriptorTest)
    java.lang.NoClassDefFoundError: org/graalvm/polyglot/Value
    ...
    2)
    initializationError(com.oracle.truffle.tck.tests.IdentityFunctionTest)
    java.lang.NoClassDefFoundError: org/graalvm/polyglot/Value
    ...

I don’t know why the class isn’t found. It does exist in the JAR:

    $ java -cp "$GRAAL_HOME/sdk/mxbuild/dists/jdk11/graal-sdk.jar" org.graalvm.polyglot.Value
    Error: Main method not found in class org.graalvm.polyglot.Value, please define the main method as:
       public static void main(String[] args)

This commit also adds truffle-tck.jar to the classpath. So far it
doesn’t make a difference, but it seems like it should be required,
since it’s needed to compile z-tck.jar, and it doesn’t hurt either.

Finally, this fixes the identity function in the language provider,
which was missing an ID. (Without this fix, the tests crash in the
ZCanonicalJsonParser before the above NoClassDefFoundError is even
reached.