WIP: OpenJDK-enabled Test Compatibility Kit
Add a bunch of JARs to the classpath, and rewrite the identity function
so it doesn’t require GraalJS, so that `make check-tck` still “works”
with non-GraalVM Javas (specifically tested with OpenJDK). The
java.lang.NoClassDefFoundError: org/graalvm/polyglot/Value persists,
though.